name: CI

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        run: timeout 160 sh create.sh || [ $? -eq 124 ]