name: CI

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        run: timeout 160s sh i2b2_ml_demo_test.sh